/**
 * Vite config generator
 */

import type { EdgeConfig } from './types.js'

/**
 * Generate vite.config.ts content from EdgeConfig
 */
export function generateViteConfig(config: EdgeConfig): string {
  const imports: string[] = []
  const plugins: string[] = []

  // Core imports
  imports.push(`import { defineConfig } from 'vite'`)
  imports.push(`import { cloudflare } from '@cloudflare/vite-plugin'`)

  // React plugin if enabled
  if (config.vite?.react) {
    imports.push(`import react from '@vitejs/plugin-react'`)
    plugins.push('    react()')
  }

  // Cloudflare plugin (always included)
  plugins.push(`    cloudflare({
      // Cloudflare Workers configuration
      // See: https://developers.cloudflare.com/workers/vite-plugin/
      // Note: This plugin automatically reads wrangler.toml
    })`)

  // Build configuration
  const buildConfig = config.vite?.build || {}
  const buildLines: string[] = []

  buildLines.push('  build: {')
  buildLines.push(`    outDir: '${buildConfig.outDir || 'dist'}',`)
  buildLines.push(`    target: '${buildConfig.target || 'esnext'}',`)
  buildLines.push(`    minify: ${buildConfig.minify ?? true},`)
  buildLines.push(`    sourcemap: ${buildConfig.sourcemap ?? true},`)
  buildLines.push('  },')

  // Generate warnings for non-ejectable features
  const warnings: string[] = []
  if (config.hooks && Object.keys(config.hooks).length > 0) {
    warnings.push(
      '// WARNING: Lifecycle hooks from edge.config.ts cannot be ejected.',
      '// You will need to implement custom build scripts to replace this functionality.'
    )
  }
  if (config.commands && Object.keys(config.commands).length > 0) {
    warnings.push(
      '// WARNING: Custom commands from edge.config.ts cannot be ejected.',
      '// You will need to add these as package.json scripts manually.'
    )
  }
  if (config.middleware && config.middleware.length > 0) {
    warnings.push(
      '// WARNING: Global middleware from edge.config.ts cannot be ejected.',
      '// You will need to implement this in your application code.'
    )
  }
  if (config.security) {
    warnings.push(
      '// WARNING: Security configuration (CSRF, headers) from edge.config.ts cannot be ejected.',
      '// You will need to implement these security features manually in your application.'
    )
  }

  // Assemble the final config
  const warningSection = warnings.length > 0 ? warnings.join('\n') + '\n//\n' : ''

  return `${imports.join('\n')}

// Generated by \`ix eject\` - Ixflare Framework
// Date: ${new Date().toISOString()}
//
// This is your ejected Vite configuration.
// You now have full control over the build process.
// See: https://vite.dev/config/
${warningSection}
export default defineConfig({
  plugins: [
${plugins.join(',\n')}
  ],
${buildLines.join('\n')}
})
`
}
