/**
 * Wrangler.toml generator
 */

import type { EdgeConfig } from './types.js'

/**
 * Generate wrangler.toml content from EdgeConfig
 */
export function generateWranglerToml(config: EdgeConfig): string {
  const lines: string[] = []

  // Header comment
  lines.push('# Generated by `ix eject` - Ixflare Framework')
  lines.push(`# Date: ${new Date().toISOString()}`)
  lines.push('#')
  lines.push('# This file was automatically generated from your edge.config.ts')
  lines.push('# You can now manage this configuration directly')
  lines.push('# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/')
  lines.push('')

  // Core settings
  lines.push(`name = "${config.name}"`)
  lines.push(`main = "dist/worker.js"`)
  lines.push(`compatibility_date = "${config.compatibilityDate}"`)

  if (config.compatibilityFlags && config.compatibilityFlags.length > 0) {
    const flags = config.compatibilityFlags.map((f) => `"${f}"`).join(', ')
    lines.push(`compatibility_flags = [${flags}]`)
  }

  // Environment variables
  if (config.env && Object.keys(config.env).length > 0) {
    lines.push('')
    lines.push('[vars]')
    for (const [key, value] of Object.entries(config.env)) {
      if (typeof value === 'string') {
        lines.push(`${key} = "${value}"`)
      } else if (typeof value === 'number') {
        lines.push(`${key} = ${value}`)
      } else if (typeof value === 'boolean') {
        lines.push(`${key} = ${value}`)
      }
    }
  }

  // D1 Databases
  if (config.bindings.d1 && config.bindings.d1.length > 0) {
    for (const db of config.bindings.d1) {
      lines.push('')
      lines.push('[[d1_databases]]')
      lines.push(`binding = "${db.binding}"`)
      lines.push(`database_name = "${db.databaseName}"`)

      if (db.databaseId) {
        lines.push(`database_id = "${db.databaseId}"`)
      } else {
        lines.push('# database_id = "YOUR_DATABASE_ID" # Run: wrangler d1 create <database_name>')
      }

      if (db.previewDatabaseId) {
        lines.push(`preview_database_id = "${db.previewDatabaseId}"`)
      }

      if (db.migrationsDir) {
        lines.push(`migrations_dir = "${db.migrationsDir}"`)
      }
    }
  }

  // KV Namespaces
  if (config.bindings.kv && config.bindings.kv.length > 0) {
    for (const kv of config.bindings.kv) {
      lines.push('')
      lines.push('[[kv_namespaces]]')
      lines.push(`binding = "${kv.binding}"`)

      if (kv.id) {
        lines.push(`id = "${kv.id}"`)
      } else {
        lines.push(
          '# id = "YOUR_KV_NAMESPACE_ID" # Run: wrangler kv:namespace create <namespace_name>'
        )
      }

      if (kv.previewId) {
        lines.push(`preview_id = "${kv.previewId}"`)
      }
    }
  }

  // R2 Buckets
  if (config.bindings.r2 && config.bindings.r2.length > 0) {
    for (const r2 of config.bindings.r2) {
      lines.push('')
      lines.push('[[r2_buckets]]')
      lines.push(`binding = "${r2.binding}"`)
      lines.push(`bucket_name = "${r2.bucketName}"`)

      if (r2.jurisdiction) {
        lines.push(`jurisdiction = "${r2.jurisdiction}"`)
      }

      if (r2.previewBucketName) {
        lines.push(`preview_bucket_name = "${r2.previewBucketName}"`)
      }
    }
  }

  // Durable Objects
  if (config.bindings.durableObjects && config.bindings.durableObjects.length > 0) {
    for (const dobj of config.bindings.durableObjects) {
      lines.push('')
      lines.push('[[durable_objects.bindings]]')
      lines.push(`name = "${dobj.name}"`)
      lines.push(`class_name = "${dobj.className}"`)

      if (dobj.scriptName) {
        lines.push(`script_name = "${dobj.scriptName}"`)
      }

      if (dobj.environment) {
        lines.push(`environment = "${dobj.environment}"`)
      }
    }
  }

  // Observability
  lines.push('')
  lines.push('# Observability')
  lines.push('upload_source_maps = true')

  // Build settings
  lines.push('')
  lines.push('# Build settings')
  lines.push('minify = true')

  return lines.join('\n') + '\n'
}
