/**
 * @module client/hydrate
 * @description Client-side island hydration utilities
 * @client-only
 *
 * This module runs in the browser and handles hydrating interactive island
 * components. It supports multiple loading strategies (immediate, idle, visible)
 * and implements per-island error boundaries to prevent cascading failures.
 *
 * @example
 * ```typescript
 * // In your client entry point:
 * import { hydrateIslands } from 'ixflare/client'
 *
 * // Hydrate all islands on the page
 * hydrateIslands()
 * ```
 */

import { createElement } from 'react'
import { hydrateRoot } from 'react-dom/client'
import type { IslandLoadStrategy } from '@/ssr/types'

/** Development mode flag */
const IS_DEV = typeof process !== 'undefined' && process.env?.NODE_ENV === 'development'

/**
 * Island component registry for runtime resolution.
 *
 * Populated by the build tool (Vite plugin) with mappings from island IDs
 * to their component modules. This enables dynamic component loading without
 * hardcoded paths.
 *
 * @example
 * ```typescript
 * // Vite plugin populates this during build:
 * setIslandRegistry({
 *   'counter': () => import('./components/Counter.client'),
 *   'search': () => import('./components/Search.client'),
 * })
 * ```
 */
let islandRegistry: Record<string, () => Promise<{ default: React.ComponentType<unknown> }>> = {}

/**
 * Sets the island component registry.
 *
 * Called by the build tool (Vite plugin in Story 4.4) to register all
 * discovered island components and their dynamic import functions.
 *
 * @param registry - Map of island IDs to component import functions
 *
 * @example
 * ```typescript
 * // Generated by vite-plugin-ixflare
 * setIslandRegistry({
 *   'counter': () => import('./islands/Counter.client'),
 *   'search-box': () => import('./islands/SearchBox.client'),
 * })
 * ```
 */
export function setIslandRegistry(
  registry: Record<string, () => Promise<{ default: React.ComponentType<unknown> }>>
): void {
  islandRegistry = registry
}

/**
 * Gets the current island registry.
 *
 * Useful for debugging and testing purposes.
 *
 * @returns Current island registry
 */
export function getIslandRegistry(): Record<
  string,
  () => Promise<{ default: React.ComponentType<unknown> }>
> {
  return islandRegistry
}

/**
 * Parses island props from JSON string with error handling.
 *
 * This is the client-side equivalent of deserializeIslandProps from the SSR module.
 * Duplicated here to avoid importing server code in client bundles.
 *
 * @param propsJson - JSON string containing serialized props
 * @param islandId - Island identifier for error messages
 * @returns Parsed props object, or null if parsing fails
 *
 * @internal
 */
function parseIslandProps(propsJson: string, islandId: string): Record<string, unknown> | null {
  try {
    return JSON.parse(propsJson)
  } catch (error) {
    console.error(`[Island Hydration Error] ${islandId}: Failed to parse props`, error)
    return null
  }
}

/**
 * Hydrates a single island component immediately.
 *
 * Loads the component module from the registry, creates a React element
 * with the provided props, and uses hydrateRoot to attach React to the
 * server-rendered HTML.
 *
 * On error, logs the failure and preserves the SSR content (graceful degradation).
 * In development mode, displays a visual warning overlay on the failed island.
 *
 * @param element - DOM element containing the server-rendered island HTML
 * @param islandId - Unique identifier for the island (used for registry lookup)
 * @param props - Deserialized props to pass to the component
 * @returns Promise that resolves when hydration is complete (or fails)
 *
 * @internal
 */
async function hydrateImmediate(
  element: Element,
  islandId: string,
  props: Record<string, unknown>
): Promise<void> {
  try {
    // Look up component in registry
    const importFn = islandRegistry[islandId]

    if (!importFn) {
      console.error(
        `[Island Hydration Error] ${islandId}: Component not found in registry. ` +
          `Ensure the island is registered via setIslandRegistry().`
      )
      return
    }

    // Dynamically import the island component
    const componentModule = await importFn()

    // Get the default export (the component)
    const Component = componentModule.default

    if (!Component) {
      console.error(
        `[Island Hydration Error] ${islandId}: No default export found in component module`
      )
      return
    }

    // Hydrate the island with React
    hydrateRoot(element, createElement(Component, props))

    if (IS_DEV) {
      console.log(`[Island Hydrated] ${islandId}`, { props })
    }
  } catch (error) {
    // Catch hydration errors and log without crashing other islands
    console.error(`[Island Hydration Error] ${islandId}:`, error)

    if (IS_DEV) {
      // In development, show warning overlay on the failed island
      showDevWarning(element, islandId)
    }

    // Island remains in server-rendered state (graceful degradation)
  }
}

/**
 * Shows a development warning overlay on a failed island.
 *
 * Creates a visible indicator that hydration failed, helping developers
 * quickly identify and debug issues during development.
 *
 * @param element - DOM element to attach warning to
 * @param islandId - Island identifier for the error message
 *
 * @internal
 */
function showDevWarning(element: Element, islandId: string): void {
  const warning = document.createElement('div')
  warning.style.cssText = `
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    padding: 8px;
    background: #fee;
    border: 1px solid #c00;
    color: #c00;
    font-size: 12px;
    font-family: monospace;
    z-index: 9999;
  `
  warning.textContent = `⚠️ Failed to hydrate island "${islandId}". Check console for details.`
  if (element.firstChild) {
    element.insertBefore(warning, element.firstChild)
  } else {
    element.appendChild(warning)
  }
}

/**
 * Schedules island hydration for browser idle time.
 *
 * Uses requestIdleCallback to defer hydration until the browser has free time,
 * improving initial page load performance. Falls back to setTimeout(fn, 1)
 * for browsers without requestIdleCallback support (e.g., Safari).
 *
 * @param element - DOM element containing the server-rendered island HTML
 * @param islandId - Unique identifier for the island
 * @param props - Deserialized props to pass to the component
 *
 * @internal
 */
function hydrateOnIdle(element: Element, islandId: string, props: Record<string, unknown>): void {
  if ('requestIdleCallback' in window) {
    requestIdleCallback(() => {
      hydrateImmediate(element, islandId, props)
    })
  } else {
    // Fallback for browsers without requestIdleCallback (Safari)
    setTimeout(() => {
      hydrateImmediate(element, islandId, props)
    }, 1)
  }
}

/**
 * Schedules island hydration when it becomes visible in the viewport.
 *
 * Uses IntersectionObserver to hydrate only when the island scrolls into view,
 * providing optimal performance for below-the-fold content. Falls back to
 * immediate hydration for browsers without IntersectionObserver support.
 *
 * @param element - DOM element containing the server-rendered island HTML
 * @param islandId - Unique identifier for the island
 * @param props - Deserialized props to pass to the component
 *
 * @internal
 */
function hydrateOnVisible(
  element: Element,
  islandId: string,
  props: Record<string, unknown>
): void {
  if ('IntersectionObserver' in window) {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            // Island is visible, hydrate it
            hydrateImmediate(element, islandId, props)
            // Stop observing after hydration
            observer.unobserve(element)
          }
        })
      },
      {
        // Trigger when at least 1px is visible, with 50px margin for preloading
        rootMargin: '50px',
        threshold: 0,
      }
    )

    observer.observe(element)
  } else {
    // Fallback for browsers without IntersectionObserver
    hydrateImmediate(element, islandId, props)
  }
}

/**
 * Hydrates all islands on the page.
 *
 * Finds all elements with `data-island` attribute and hydrates them according
 * to their loading strategy (immediate, idle, or visible).
 *
 * This function should be called once in your client entry point after the
 * island registry has been populated by the build tool.
 *
 * @param selector - CSS selector to find island elements (default: '[data-island]')
 *
 * @example
 * ```typescript
 * // src/entry-client.ts
 * import { hydrateIslands, setIslandRegistry } from 'ixflare/client'
 *
 * // Registry is populated by vite-plugin-ixflare
 * setIslandRegistry(window.__ISLAND_REGISTRY__)
 *
 * // Hydrate all islands
 * hydrateIslands()
 * ```
 *
 * @example
 * ```typescript
 * // Manual hydration with custom selector
 * hydrateIslands('[data-custom-island]')
 * ```
 */
export function hydrateIslands(selector = '[data-island]'): void {
  // Find all island markers in the DOM
  const islands = document.querySelectorAll(selector)

  if (IS_DEV) {
    console.log(`[Islands] Found ${islands.length} islands to hydrate`)
  }

  islands.forEach((element) => {
    const islandId = element.getAttribute('data-island')
    const propsJson = element.getAttribute('data-props') || '{}'
    const loadStrategy = (element.getAttribute('data-load') as IslandLoadStrategy) || 'immediate'

    if (!islandId) {
      console.error('[Island Hydration Error] Missing data-island attribute')
      return
    }

    // Parse props with error handling
    const props = parseIslandProps(propsJson, islandId)
    if (props === null) {
      return // Error already logged
    }

    // Hydrate based on loading strategy
    if (loadStrategy === 'immediate') {
      hydrateImmediate(element, islandId, props)
    } else if (loadStrategy === 'idle') {
      hydrateOnIdle(element, islandId, props)
    } else if (loadStrategy === 'visible') {
      hydrateOnVisible(element, islandId, props)
    } else {
      console.warn(
        `[Island Hydration Warning] ${islandId}: Unknown load strategy "${loadStrategy}", using immediate`
      )
      hydrateImmediate(element, islandId, props)
    }
  })
}

/**
 * Hydrates a single island by its ID.
 *
 * Useful for manually hydrating specific islands after dynamic content loads,
 * or for re-hydrating islands that were added to the DOM after initial page load.
 *
 * @param islandId - The unique identifier of the island to hydrate
 *
 * @example
 * ```typescript
 * // After dynamically loading content with a new island
 * hydrateIslandById('dynamic-counter-1')
 * ```
 */
export function hydrateIslandById(islandId: string): void {
  const element = document.querySelector(`[data-island="${islandId}"]`)

  if (!element) {
    console.error(`[Island Hydration Error] Island "${islandId}" not found in DOM`)
    return
  }

  const propsJson = element.getAttribute('data-props') || '{}'

  const props = parseIslandProps(propsJson, islandId)
  if (props === null) {
    return // Error already logged
  }

  hydrateImmediate(element, islandId, props)
}
